openapi: 3.0.0
info:
  description: RAV API
  version: "1.0.0-oas3"
  title: RAV API
  contact:
    email: name@mail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /configuration:
    get:
      tags:
        - developers
      summary: current configuration
      operationId: getConfiguration
      description: |
        Returns the current configuration of the RAV module
      responses:
        '200':
          description: SUCCESS,
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configuration'
    post:
      tags:
        - developers
      summary: adds an inventory item
      operationId: setConfiguration
      description: Sets a new configuration on the RAV module
      responses:
        '200':
          description: configuration received
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configuration'
        '400':
          description: malformed JSON content
        '401':
          description: unsupported request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configuration'
        description: New configuration for the module
  /command:
    get:
      tags:
        - developers
      summary: command history
      operationId: getCommand
      description: |
        Returns the command history RAV module
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandHistory'
    post:
      tags:
        - developers
      summary: new command
      operationId: setCommand
      description: Executes a new command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newCommand'
        description: Executes new command
      responses:
        '200':
          description: command received'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/receivedCommand'
        '400':
          description: malformed JSON content
        '401':
          description: unsupported request
  /report_dump:
    get:
      tags:
        - developers
      summary: dump results
      operationId: getResultsCommand
      description: |
        Returns the validation results in JSON format
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResults'
    
servers:
  - url: 'https://virtserver.swaggerhub.com/myRAVorg/RAV_latest/1.0.0'
components:
  schemas:
    configuration:
      type: object
      required:
        - topics
        - publish
      properties:
        topics:
          type: array
          items:
            $ref: '#/components/schemas/topic'
        publish:
          type: array
          items:
            $ref: '#/components/schemas/publishtopic'
    commandHistory:
      type: object
      properties:
        command_history:
          type: array
          items:
            $ref: '#/components/schemas/commandInstance'
    newCommand:
      type: object
      required:
        - command
      properties:
        command:
          type: string
          example: start / stop
    receivedCommand:
      type: object
      required: 
      - received_command
      - status
      properties:
        received_command:
          type: string
          example: start / stop
        status:
          type: string
          example: executing / unsupported / error
    topic:
      type: object
      required:
        - brokerAddr
        - topic
        - metric
      properties:
        brokerAddr:
          type: string
          example: '127.0.0.1:9092'
        topic:
          type: string
          example: metric_1_topic
        metric:
          type: string
          example: metric_1_name
    publishtopic:
      type: object
      required:
        - brokerAddr
        - topic
        - kpi
      properties:
        brokerAddr:
          type: string
          example: '127.0.0.1:9092'
        topic:
          type: string
          example: output_kpi_1_topic
        kpi:
          type: string
          example: output_kpi_1_name
    commandInstance:
      type: object
      properties:
        timestamp:
          type: number
          example: 1578563340.3533046
        command:
          type: string
          example: start / stop
        status:
          type: string
          example: executing / not implemented yet / error
    validationResults:
      type: object
      properties:
        information:
          type: string
          example: 'Monday January 13, 2020'
        additional_information:
          type: string
          example: 'UC#1: Example'
        validation_results:
          type: array
          items:
            $ref: '#/components/schemas/validationResultsInstance'
    validationResultsInstance:
      type: object
      properties:
        index:
          type: number
          example: 1
        messages:
          type: array
          items:
            type: string
            example: 'typical message format'
        number_of_messages:
          type: number
          example: 128
        topic:
          type: string
          example: '/app/vertical_kpi_1'
        validation:
          type: boolean
          example: true