openapi: 3.0.0
info:
  title: RAV API
  description: RAV API
  contact:
    email: name@mail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
servers:
- url: https://virtserver.swaggerhub.com/myRAVorg/RAV_latest/1.0.0
tags:
- name: developers
  description: Operations available to regular developers
paths:
  /configuration/{expID}:
    get:
      tags:
      - developers
      summary: get the configuration for an experiment
      description: |
        Returns the current configuration of the RAV module
      operationId: getConfigurationExp
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS,
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configurationDict'
    post:
      tags:
      - developers
      summary: adds configuration for an experiment
      description: Sets a new configuration on the RAV module
      operationId: setConfigurationExp
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: New configuration for the module
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/configurationDict'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/configurationResp'
        "400":
          description: Malformed JSON content
        "409":
          description: Conflict
  /queue:
    get:
      tags:
      - developers
      summary: dump list of active RAV instances
      description: |
        Returns the list of all the rav instances
      operationId: getResultsCommand
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResultsList'
  /queue/{expID}:
    get:
      tags:
      - developers
      summary: dump results for specific experiment
      description: |
        Returns the results of the specific experiment
      operationId: getExpResults
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationResultsInstance'
  /queue/{expID}/{tcID}:
    get:
      tags:
      - developers
      summary: dump results for specific testcase
      description: |
        Returns the results of the specific testcase
      operationId: getTcResults
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tcID
        in: path
        description: |
          Identifier of testcase
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/validationTestcaseResultsInstance'
        "404":
          description: FAIL
  /terminate/{expID}:
    get:
      tags:
      - developers
      summary: terminate current step of experiment
      description: |
        Terminates the current step of the experiment
      operationId: terminateCurrentStep
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandResponse'
  /terminate/{expID}/{tcID}:
    get:
      tags:
      - developers
      summary: terminate current testcase of experiment
      description: |
        Terminates the current testcase of the experiment
      operationId: terminateCurrentTestcase
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tcID
        in: path
        description: |
          Identifier of testcase
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandResponse'
        "404":
          description: FAIL
  /validate/{expID}/{tcID}:
    get:
      tags:
      - developers
      summary: start testcase validation
      description: |
        Start the validation of the requests testcase
      operationId: startTestcaseValidation
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: tcID
        in: path
        description: |
          Identifier of testcase
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandResponse'
        "404":
          description: FAIL
  /step/{expID}:
    get:
      tags:
      - developers
      summary: add step to experiment
      description: |
        Adds additional step to experiment
      operationId: addStepToExp
      parameters:
      - name: expID
        in: path
        description: |
          Identifier of experiment
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandResponse'
components:
  schemas:
    configurationDict:
      required:
      - expID
      - testcases
      - vertical
      type: object
      properties:
        vertical:
          type: string
          example: Smart Transportation
        expID:
          type: string
          example: ea0b4e14-8b54-4a7d-8635-8e0dacad334b
        testcases:
          type: array
          items:
            $ref: '#/components/schemas/configurationDict_testcases'
    configurationResp:
      type: object
      properties:
        experiment_found:
          type: boolean
          example: true
        status:
          type: string
          example: running
        instances_list:
          type: array
          items:
            $ref: '#/components/schemas/configurationDict'
    configuration:
      required:
      - publish
      - topics
      type: object
      properties:
        topics:
          type: array
          items:
            $ref: '#/components/schemas/topic'
        publish:
          type: array
          items:
            $ref: '#/components/schemas/publishtopic'
    topic:
      required:
      - brokerAddr
      - metric
      - topic
      type: object
      properties:
        brokerAddr:
          type: string
          example: 127.0.0.1:9092
        topic:
          type: string
          example: metric_1_topic
        metric:
          type: string
          example: metric_1_name
    publishtopic:
      required:
      - brokerAddr
      - kpi
      - topic
      type: object
      properties:
        brokerAddr:
          type: string
          example: 127.0.0.1:9092
        topic:
          type: string
          example: output_kpi_1_topic
        kpi:
          type: string
          example: output_kpi_1_name
    validationResultsList:
      type: array
      items:
        $ref: '#/components/schemas/validationResultsInstance'
    validationResultsInstance:
      type: object
      properties:
        expID:
          type: string
          example: 123af1rcxhauq13-13r142f1-13f13f-121e
        testcases:
          type: array
          items:
            $ref: '#/components/schemas/configurationDict_testcases'
        steps:
          type: number
          example: 2
        added:
          type: string
          example: 02/06/2020, 04:22:36
        finished:
          type: string
          example: 02/06/2020, 04:23:47
        status:
          type: string
          example: finished
        validation:
          $ref: '#/components/schemas/validationResults'
    validationTestcaseResultsInstance:
      type: object
      properties:
        tcID:
          type: string
          example: 5e28a691-2a58-432f-a730-0fc98a9e75b8
        configuration:
          $ref: '#/components/schemas/configuration'
        steps:
          type: number
          example: 2
        added:
          type: string
          example: 02/06/2020, 04:22:36
        finished:
          type: string
          example: 02/06/2020, 04:23:47
        status:
          type: string
          example: finished
        validation:
          $ref: '#/components/schemas/validationResults'
    validationResults:
      type: object
      additionalProperties: true
    commandResponse:
      type: object
      properties:
        expID:
          type: string
          example: 123af1rcxhauq13-13r142f1-13f13f-121e
        tcID:
          type: string
          example: 141af25ae25131b-13a112af-bcf259-f619
        status:
          type: string
          example: running
    configurationDict_testcases:
      type: object
      properties:
        tcID:
          type: string
          example: 5e28a691-2a58-432f-a730-0fc98a9e75b8
        configuration:
          $ref: '#/components/schemas/configuration'
